client_configs:
  train_configs:
    # Local trainer with gradient weighting
    trainer: "WeightedGradientTrainer"
    mode: "epoch"
    num_local_epochs: 5
    optim: "SGD"
    optim_args:
      lr: 0.01
    # Loss function
    loss_fn_path: "./resources/loss/celoss.py"
    loss_fn_name: "CELoss"
    # Client validation
    do_validation: False
    do_pre_validation: False
    metric_path: "./resources/metric/acc.py"
    metric_name: "accuracy"
    # Gradient weighting configuration
    use_gradient_weighting: True
    # Importance weighting (IW) options - Generalized Power Transformation
    use_uniform_weights: False       # Use uniform weights (all weights = 1.0)
    use_interpolated_weights: False  # Use interpolated IW: p_global / {(1-λ)*p_local + λ*p_global}
    lambda_interp: 0.5               # Interpolation parameter λ ∈ [0,1] (0=standard IW, 1=uniform)
    use_power: True                  # Enable power transformation: (weight)^power_lambda
    power_lambda: 0.0              # Power parameter (0.5=sqrt, 1.0=no transform, 0=uniform)
    # Differential privacy
    use_dp: False
    epsilon: 1
    clip_grad: False
    clip_value: 1
    clip_norm: 1
    # Data loader
    train_batch_size: 64
    val_batch_size: 64
    train_data_shuffle: True
    val_data_shuffle: False

  model_configs:
    model_path: "./resources/model/resnet.py"
    model_name: "ResNet18"

  comm_configs:
    compressor_configs:
      enable_compression: False
      # Used if enable_compression is True
      lossy_compressor:  "SZ2Compressor"
      lossless_compressor: "blosc"
      error_bounding_mode: "REL"
      error_bound: 1e-3
      param_cutoff: 1024

server_configs:
  num_clients: 10
  scheduler: "SyncScheduler"
  scheduler_kwargs:
    same_init_model: True
  aggregator: "FedAvgAggregator"
  aggregator_kwargs:
    client_weights_mode: "equal"
  device: "cuda"
  num_global_epochs: 100
  logging_output_dirname: "./output"
  logging_output_filename: "result"
  comm_configs:
    grpc_configs:
      server_uri: localhost:50051
      max_message_size: 1048576
      use_ssl: False
  val_data_configs:
    dataset_path: "./resources/dataset/cifar10_dataset.py"
    dataset_name: "get_cifar10_val_global" 