client_id: "Client1"
train_configs:
  # Device
  device: "cuda"
  # Logging and outputs
  logging_output_dirname: "./output"
  logging_output_filename: "result"

# Local dataset
data_configs:
  dataset_path: "../resources/dataset/agnews_dataset.py"
  dataset_name: "get_agnews"
  dataset_kwargs:
    num_clients: 10
    client_id: 0
    partition_strategy: "dirichlet_noniid"
    # Dirichlet parameters to control data distribution heterogeneity
    alpha1: 10.0        # Controls client sample size distribution (higher = more even)
    alpha2: 0.5         # Controls class distribution per client (higher = more even)
    visualization: True
    output_dirname: "./output"
    output_filename: "agnews_visualization.pdf"

wandb_configs:
  enable_wandb: True
  project: "appfl"
  exp_name: "appfl-agnews"

comm_configs:
  grpc_configs:
    server_uri: localhost:50051
    max_message_size: 1048576
    use_ssl: False 